-- ==============================================================================
-- COME TO EAT CAFE - COMPLETE SUPABASE POSTGRESQL SCHEMA & INITIAL SEED DATA
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query -> Run)
-- ==============================================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  phone TEXT,
  role TEXT DEFAULT 'user',
  is_blocked INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ADMINS & STAFF TABLE
CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  branch_id INTEGER DEFAULT 1,
  pending_branch_id INTEGER,
  transfer_status TEXT DEFAULT 'none',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BRANCHES TABLE
CREATE TABLE IF NOT EXISTS branches (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  code TEXT UNIQUE NOT NULL,
  address TEXT NOT NULL,
  phone TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  image_url TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. FOOD ITEMS TABLE
CREATE TABLE IF NOT EXISTS food_items (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  price DECIMAL NOT NULL,
  discount_price DECIMAL,
  is_veg INTEGER DEFAULT 1,
  is_available INTEGER DEFAULT 1,
  prep_time TEXT DEFAULT '15-20 min',
  is_featured INTEGER DEFAULT 0,
  rating DECIMAL DEFAULT 4.5,
  rating_count INTEGER DEFAULT 12,
  image_url TEXT,
  tags TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. FOOD ADDONS TABLE
CREATE TABLE IF NOT EXISTS food_addons (
  id SERIAL PRIMARY KEY,
  food_id INTEGER NOT NULL REFERENCES food_items(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL,
  is_required INTEGER DEFAULT 0
);

-- 7. USER ADDRESSES TABLE
CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label TEXT DEFAULT 'Home',
  street TEXT NOT NULL,
  city TEXT NOT NULL,
  landmark TEXT,
  phone TEXT NOT NULL,
  is_default INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  user_id BIGINT,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT NOT NULL,
  delivery_type TEXT DEFAULT 'delivery',
  delivery_address TEXT,
  delivery_address_json TEXT,
  total_amount NUMERIC(10,2) DEFAULT 0,
  item_total NUMERIC(10,2) DEFAULT 0,
  tax_amount NUMERIC(10,2) DEFAULT 0,
  taxes NUMERIC(10,2) DEFAULT 0,
  delivery_fee NUMERIC(10,2) DEFAULT 0,
  discount_amount NUMERIC(10,2) DEFAULT 0,
  coupon_code TEXT,
  final_amount NUMERIC(10,2) NOT NULL,
  payment_method TEXT DEFAULT 'UPI',
  payment_status TEXT DEFAULT 'completed',
  order_status TEXT DEFAULT 'Order Placed',
  cancellation_reason TEXT,
  estimated_delivery_minutes INTEGER DEFAULT 30,
  branch_id BIGINT DEFAULT 1,
  branch_name TEXT DEFAULT 'Indiranagar (Flagship)',
  items_json TEXT,
  items JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all order columns exist even if table was created previously
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address_json TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS item_total NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS taxes NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'UPI';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'completed';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_status TEXT DEFAULT 'Order Placed';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS estimated_delivery_minutes INTEGER DEFAULT 30;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS branch_id BIGINT DEFAULT 1;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS branch_name TEXT DEFAULT 'Indiranagar (Flagship)';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items_json TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items JSONB;

-- 9. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS order_items (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  food_id INTEGER REFERENCES food_items(id),
  food_name TEXT NOT NULL,
  unit_price DECIMAL NOT NULL,
  quantity INTEGER NOT NULL,
  subtotal DECIMAL NOT NULL,
  selected_addons_json TEXT
);

-- 10. ORDER STATUS HISTORY TABLE
CREATE TABLE IF NOT EXISTS order_status_history (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  old_status TEXT,
  new_status TEXT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  user_id REFERENCES users(id),
  amount DECIMAL NOT NULL,
  payment_method TEXT NOT NULL,
  transaction_id TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'successful',
  gateway_response_json TEXT,
  refund_status TEXT DEFAULT 'none',
  refund_amount DECIMAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. DELIVERY ORDERS TABLE
CREATE TABLE IF NOT EXISTS delivery_orders (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  driver_name TEXT NOT NULL,
  driver_phone TEXT NOT NULL,
  current_status TEXT DEFAULT 'assigned',
  live_lat DECIMAL,
  live_lng DECIMAL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. COUPONS TABLE
CREATE TABLE IF NOT EXISTS coupons (
  id SERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT NOT NULL,
  discount_value DECIMAL NOT NULL,
  min_order_value DECIMAL DEFAULT 0,
  max_discount DECIMAL,
  start_date DATE,
  end_date DATE,
  expires_at TIMESTAMPTZ,
  is_active INTEGER DEFAULT 1,
  times_used INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. OFFER BANNERS TABLE
CREATE TABLE IF NOT EXISTS offer_banners (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  tag TEXT NOT NULL DEFAULT 'PROMO',
  description TEXT,
  image_url TEXT,
  button_text TEXT DEFAULT 'Explore Menu',
  target_category TEXT,
  bg_color TEXT DEFAULT '#85926B',
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  branch_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. HERO BANNER SLIDES TABLE
CREATE TABLE IF NOT EXISTS hero_slides (
  id SERIAL PRIMARY KEY,
  tag TEXT NOT NULL,
  script TEXT NOT NULL,
  title TEXT NOT NULL,
  desc_text TEXT NOT NULL,
  image_url TEXT,
  button_text TEXT DEFAULT 'Order Now',
  bg_color TEXT DEFAULT '#85926B',
  accent_text TEXT,
  target_category TEXT DEFAULT 'Burgers and Sandwiches',
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  food_id INTEGER REFERENCES food_items(id),
  is_approved INTEGER DEFAULT 1,
  branch_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. RESTAURANT SETTINGS TABLE
CREATE TABLE IF NOT EXISTS restaurant_settings (
  id SERIAL PRIMARY KEY,
  setting_key TEXT UNIQUE NOT NULL,
  setting_value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ENABLE SUPABASE REALTIME REPLICATION FOR INSTANT LIVE REFLECTION
-- ==============================================================================
DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE orders; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE food_items; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE hero_slides; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE offer_banners; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE categories; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE branches; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE coupons; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE restaurant_settings; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE reviews; EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;

-- ==============================================================================
-- DISABLE ROW LEVEL SECURITY (RLS) FOR PUBLIC ACCESS VIA ANON KEY
-- ==============================================================================
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE food_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE food_addons DISABLE ROW LEVEL SECURITY;
ALTER TABLE addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE coupons DISABLE ROW LEVEL SECURITY;
ALTER TABLE offer_banners DISABLE ROW LEVEL SECURITY;
ALTER TABLE hero_slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE restaurant_settings DISABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- SEED INITIAL DATA
-- ==============================================================================

-- Branches
INSERT INTO branches (id, name, code, address, phone, is_active) VALUES
(1, 'Indiranagar (Flagship)', 'INDIRA', '100 Feet Rd, Indiranagar, Bengaluru, 560038', '+91 98765 43210', 1),
(2, 'Koramangala', 'KORA', '80 Feet Rd, 5th Block, Koramangala, Bengaluru, 560095', '+91 98765 43211', 1),
(3, 'HSR Layout', 'HSR', '27th Main Rd, Sector 1, HSR Layout, Bengaluru, 560102', '+91 98765 43212', 1),
(4, 'Whitefield', 'WHITE', 'ITPB Main Road, Whitefield, Bengaluru, 560066', '+91 98765 43213', 1)
ON CONFLICT (id) DO NOTHING;

-- Restaurant Settings
INSERT INTO restaurant_settings (setting_key, setting_value) VALUES
('timing_text', 'Open Daily: 10:00 AM – 11:30 PM'),
('days_open', 'Monday – Sunday: 10:00 AM – 11:30 PM (No weekly off)'),
('delivery_text', 'Express 30 Min Delivery'),
('contact_address', '100 Feet Rd, Indiranagar, Bengaluru, 560038'),
('contact_phone', '+91 98765 43210'),
('contact_email', 'hello@cometoeat.com')
ON CONFLICT (setting_key) DO NOTHING;

-- Admin & Employee Staff
INSERT INTO admins (id, name, email, password, role, branch_id) VALUES
(1, 'Executive Admin', 'admin@cometoeat.com', 'admin123', 'admin', 1),
(2, 'Chef Vikram (Kitchen Staff)', 'chef@cometoeat.com', 'employee123', 'employee', 1)
ON CONFLICT (id) DO NOTHING;

-- Categories
INSERT INTO categories (id, name, slug, image_url, description, sort_order, is_active) VALUES
(1, 'Burgers and Sandwiches', 'burgers-and-sandwiches', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80', 'Flame-grilled smash burgers, gourmet subs, and toasted panini', 1, 1),
(2, 'Momos', 'momos', 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', 'Steamed, fried, and pan-seared Darjeeling momos', 2, 1),
(3, 'Maggi', 'maggi', 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80', 'Classic, cheesy, and spicy loaded cafe-style Maggi', 3, 1),
(4, 'Snacks', 'snacks', 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80', 'Crispy french fries, nuggets, garlic bread, and finger bites', 4, 1),
(5, 'Cold Beverages', 'cold-beverages', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80', 'Chilled iced coffees, cold brews, and fruit coolers', 5, 1),
(6, 'Mojito', 'mojito', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80', 'Refreshing muddled mint & lime mocktails', 6, 1),
(7, 'Pizzas', 'pizzas', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80', 'Wood-fired hand-tossed Neapolitan pizzas', 7, 1),
(8, 'Boba Tea', 'boba-tea', 'https://images.unsplash.com/photo-1558857563-b37cf5c490a6?auto=format&fit=crop&w=800&q=80', 'Authentic Taiwanese boba & bubble milk teas', 8, 1),
(9, 'Pasta', 'pasta', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80', 'Italian creamy Alfredo, Arrabbiata, and Pink sauce pastas', 9, 1)
ON CONFLICT (id) DO NOTHING;

-- Food Items
INSERT INTO food_items (id, name, slug, description, category_id, price, discount_price, is_veg, is_featured, rating, image_url, is_available) VALUES
(1, 'Double Smash Gourmet Burger', 'double-smash-burger', 'Double crisp-edged smash patties, molten cheddar, caramelized butter onions, and house secret sauce on brioche.', 1, 249, 219, 0, 1, 4.8, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80', 1),
(2, 'Truffle Mushroom Swiss Burger', 'truffle-mushroom-burger', 'Sauteed wild mushrooms, swiss cheese melt, and white truffle aioli on toasted sesame bun.', 1, 269, 239, 1, 1, 4.7, 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80', 1),
(3, 'Brown Sugar Tiger Boba Milk', 'brown-sugar-tiger-boba', 'Slow-simmered dark caramel streaks, organic fresh dairy, and warm chewy tapioca pearls.', 8, 219, 199, 1, 1, 4.9, 'https://images.unsplash.com/photo-1558857563-b37cf5c490a6?auto=format&fit=crop&w=800&q=80', 1),
(4, 'Matcha Green Tea Cheese Foam', 'matcha-cheese-foam', 'Ceremonial Uji matcha tea blended with fresh milk and topped with sea salt cheese foam.', 8, 239, 209, 1, 0, 4.6, 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80', 1),
(5, 'Steamed Darjeeling Chicken Momos', 'steamed-chicken-momos', 'Hand-folded juicy minced chicken momos served with fiery red chili sesame chutney.', 2, 189, 169, 0, 1, 4.8, 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', 1),
(6, 'Pan-Fried Schezwan Paneer Momos', 'pan-fried-paneer-momos', 'Crispy pan-seared cottage cheese momos tossed in spicy house schezwan sauce.', 2, 179, 159, 1, 0, 4.7, 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80', 1),
(7, 'Neapolitan Margherita Pizza', 'neapolitan-margherita', 'San Marzano tomato sauce, fresh buffalo mozzarella, virgin olive oil, and sweet basil leaves.', 7, 349, 319, 1, 1, 4.8, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80', 1),
(8, 'Belgian Choco Molten Lava Cake', 'belgian-choco-lava', 'Warm dark Belgian chocolate cake with a gooey oozing molten chocolate core.', 4, 179, 149, 1, 1, 4.9, 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80', 1)
ON CONFLICT (id) DO NOTHING;

-- Hero Slides
INSERT INTO hero_slides (id, tag, script, title, desc_text, image_url, button_text, bg_color, target_category, sort_order, is_active) VALUES
(1, 'ORGANIC BLEND', 'Healthy Smoothie', 'Good Food. Good Mood. Come To Eat.', 'Crafted with ripe hand-picked fruits, Greek yogurt, and pure mountain honey. Fuel your day with vibrant goodness.', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80', 'Explore Menu', '#949E7C', 'Boba Tea & Drinks', 1, 1),
(2, 'CHEF SIGNATURE', 'Gourmet Burgers', 'Flame-Grilled Juicy Smash Burgers', 'Double crisp-edged patties, molten aged cheddar, caramelized butter onions, and house secret sauce on warm brioche.', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80', 'Explore Burgers', '#8B9474', 'Burgers and Sandwiches', 2, 1),
(3, 'TAIWANESE AUTHENTIC', 'Tiger Milk Boba', 'Brown Sugar Tapioca Bubble Tea', 'Slow-simmered dark caramel streaks, organic fresh dairy, and warm chewy tapioca pearls brewed fresh daily.', 'https://images.unsplash.com/photo-1558857563-b37cf5c490a6?auto=format&fit=crop&w=900&q=80', 'Taste Boba', '#969F82', 'Boba Tea & Drinks', 3, 1)
ON CONFLICT (id) DO NOTHING;

-- Offer Banners
INSERT INTO offer_banners (id, title, tag, description, image_url, button_text, target_category, bg_color, is_active) VALUES
(1, 'Flat 50% OFF First Order', 'WELCOME SPECIAL', 'Unlock 50% discount on gourmet smash burgers, momos, and fresh coolers prepared live.', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80', 'Order Burgers Now', 'Burgers and Sandwiches', '#85926B', 1),
(2, 'Free Boba Topping & Drink Upgrade', 'BOBA FESTIVAL', 'Buy any signature Brown Sugar Tiger Boba and receive a complimentary cheese foam top layer.', 'https://images.unsplash.com/photo-1558857563-b37cf5c490a6?auto=format&fit=crop&w=800&q=80', 'Explore Boba Drinks', 'Boba Tea & Drinks', '#969F82', 1),
(3, 'Darjeeling Momo Platter Combo', 'SNACKING BUNDLE', 'Order 2 Momo plates & get 1 fresh Lime Mojito completely free with rapid table delivery.', 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80', 'View Momo Combos', 'Momos & Dumplings', '#8B9474', 1)
ON CONFLICT (id) DO NOTHING;

-- Coupons
INSERT INTO coupons (id, code, discount_type, discount_value, min_order_value, max_discount, is_active) VALUES
(1, 'WELCOME50', 'percentage', 50, 200, 150, 1),
(2, 'FEAST100', 'fixed', 100, 499, 100, 1),
(3, 'FREESHIP', 'fixed', 40, 150, 40, 1)
ON CONFLICT (id) DO NOTHING;

-- Sample Reviews
INSERT INTO reviews (id, user_name, rating, comment, is_approved) VALUES
(1, 'Ananya Sharma', 5, 'The Double Smash Burger is truly the best burger in Indiranagar! Perfectly juicy and fresh brioche.', 1),
(2, 'Rahul Mehta', 5, 'Brown Sugar Tiger Boba is authentic Taiwanese quality. Chewy tapioca and rich milk balance.', 1),
(3, 'Priya Nair', 5, 'Super fast 25-minute delivery! The Darjeeling momos were piping hot with great chili sauce.', 1)
ON CONFLICT (id) DO NOTHING;
